//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEWUX.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_maestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden_maestro()
        {
            this.orden_detalle = new HashSet<orden_detalle>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creada { get; set; }
        public string estados { get; set; }
    
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_detalle> orden_detalle { get; set; }
    }
}
